# Schema for the configuration files of the Legal module.

legal.settings:
  type: config_object
  label: 'Legal settings'
  mapping:
    registration_terms_style:
      type: integer
      label: 'Registration T&C display style'
    registration_container:
      type: integer
      label: 'Registration T&C wrapper'
    login_terms_style:
      type: integer
      label: 'Login T&C display style'
    login_container:
      type: integer
      label: 'Login T&C wrapper'
    user_profile_display:
      type: boolean
      label: 'Show T&Cs on user profile edit pages'
    accept_every_login:
      type: boolean
      label: 'Ask to accept T&Cs on every login'
    except_roles:
      type: sequence
      label: 'Exempt user roles'
    registration_modal_terms:
      type: boolean
      label: 'How to display the T&Cs when a user clicks on the link on the registration form.'
    login_modal_terms:
      type: boolean
      label: 'How to display the T&Cs when a user clicks on the link on the login form.'
