id: d7_legal_settings
label: Legal settings
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - legal_display
  source_module: legal
process:
  registration_terms_style: legal_display
  login_terms_style: legal_display
  user_profile_display: legal_user_profile_display
  accept_every_login: legal_accept_every_login
  except_roles: legal_except_roles
  registration_modal_terms: legal_lightbox2
  login_modal_terms: legal_lightbox2
  registration_container:
      plugin: default_value
      default_value: 0
  login_container:
      plugin: default_value
      default_value: 0
destination:
  plugin: config
  config_name: legal.settings
dependencies:
  module:
    - legal
    - migrate_drupal
  enforced:
    module:
      - legal
